window.esdocSearchIndex = [
  [
    "fluent-dom/src/dom_localization.js~domlocalization",
    "class/src/dom_localization.js~DOMLocalization.html",
    "<span>DOMLocalization</span> <span class=\"search-result-import-path\">fluent-dom/src/dom_localization.js</span>",
    "class"
  ],
  [
    "fluent-dom/src/localization.js~localization",
    "class/src/localization.js~Localization.html",
    "<span>Localization</span> <span class=\"search-result-import-path\">fluent-dom/src/localization.js</span>",
    "class"
  ],
  [
    "fluent-dom/src/overlay.js~translateelement",
    "function/index.html#static-function-translateElement",
    "<span>translateElement</span> <span class=\"search-result-import-path\">fluent-dom/src/overlay.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/dom_localization.js",
    "file/src/dom_localization.js.html",
    "src/dom_localization.js",
    "file"
  ],
  [
    "src/dom_localization.js~domlocalization#applytranslations",
    "class/src/dom_localization.js~DOMLocalization.html#instance-method-applyTranslations",
    "src/dom_localization.js~DOMLocalization#applyTranslations",
    "method"
  ],
  [
    "src/dom_localization.js~domlocalization#connectroot",
    "class/src/dom_localization.js~DOMLocalization.html#instance-method-connectRoot",
    "src/dom_localization.js~DOMLocalization#connectRoot",
    "method"
  ],
  [
    "src/dom_localization.js~domlocalization#constructor",
    "class/src/dom_localization.js~DOMLocalization.html#instance-constructor-constructor",
    "src/dom_localization.js~DOMLocalization#constructor",
    "method"
  ],
  [
    "src/dom_localization.js~domlocalization#disconnectroot",
    "class/src/dom_localization.js~DOMLocalization.html#instance-method-disconnectRoot",
    "src/dom_localization.js~DOMLocalization#disconnectRoot",
    "method"
  ],
  [
    "src/dom_localization.js~domlocalization#getattributes",
    "class/src/dom_localization.js~DOMLocalization.html#instance-method-getAttributes",
    "src/dom_localization.js~DOMLocalization#getAttributes",
    "method"
  ],
  [
    "src/dom_localization.js~domlocalization#getkeysforelement",
    "class/src/dom_localization.js~DOMLocalization.html#instance-method-getKeysForElement",
    "src/dom_localization.js~DOMLocalization#getKeysForElement",
    "method"
  ],
  [
    "src/dom_localization.js~domlocalization#gettranslatables",
    "class/src/dom_localization.js~DOMLocalization.html#instance-method-getTranslatables",
    "src/dom_localization.js~DOMLocalization#getTranslatables",
    "method"
  ],
  [
    "src/dom_localization.js~domlocalization#mutationobserver",
    "class/src/dom_localization.js~DOMLocalization.html#instance-member-mutationObserver",
    "src/dom_localization.js~DOMLocalization#mutationObserver",
    "member"
  ],
  [
    "src/dom_localization.js~domlocalization#observerconfig",
    "class/src/dom_localization.js~DOMLocalization.html#instance-member-observerConfig",
    "src/dom_localization.js~DOMLocalization#observerConfig",
    "member"
  ],
  [
    "src/dom_localization.js~domlocalization#onchange",
    "class/src/dom_localization.js~DOMLocalization.html#instance-method-onChange",
    "src/dom_localization.js~DOMLocalization#onChange",
    "method"
  ],
  [
    "src/dom_localization.js~domlocalization#pauseobserving",
    "class/src/dom_localization.js~DOMLocalization.html#instance-method-pauseObserving",
    "src/dom_localization.js~DOMLocalization#pauseObserving",
    "method"
  ],
  [
    "src/dom_localization.js~domlocalization#pendingelements",
    "class/src/dom_localization.js~DOMLocalization.html#instance-member-pendingElements",
    "src/dom_localization.js~DOMLocalization#pendingElements",
    "member"
  ],
  [
    "src/dom_localization.js~domlocalization#pendingraf",
    "class/src/dom_localization.js~DOMLocalization.html#instance-member-pendingrAF",
    "src/dom_localization.js~DOMLocalization#pendingrAF",
    "member"
  ],
  [
    "src/dom_localization.js~domlocalization#resumeobserving",
    "class/src/dom_localization.js~DOMLocalization.html#instance-method-resumeObserving",
    "src/dom_localization.js~DOMLocalization#resumeObserving",
    "method"
  ],
  [
    "src/dom_localization.js~domlocalization#roots",
    "class/src/dom_localization.js~DOMLocalization.html#instance-member-roots",
    "src/dom_localization.js~DOMLocalization#roots",
    "member"
  ],
  [
    "src/dom_localization.js~domlocalization#setattributes",
    "class/src/dom_localization.js~DOMLocalization.html#instance-method-setAttributes",
    "src/dom_localization.js~DOMLocalization#setAttributes",
    "method"
  ],
  [
    "src/dom_localization.js~domlocalization#translateelements",
    "class/src/dom_localization.js~DOMLocalization.html#instance-method-translateElements",
    "src/dom_localization.js~DOMLocalization#translateElements",
    "method"
  ],
  [
    "src/dom_localization.js~domlocalization#translatefragment",
    "class/src/dom_localization.js~DOMLocalization.html#instance-method-translateFragment",
    "src/dom_localization.js~DOMLocalization#translateFragment",
    "method"
  ],
  [
    "src/dom_localization.js~domlocalization#translatemutations",
    "class/src/dom_localization.js~DOMLocalization.html#instance-method-translateMutations",
    "src/dom_localization.js~DOMLocalization#translateMutations",
    "method"
  ],
  [
    "src/dom_localization.js~domlocalization#translateroots",
    "class/src/dom_localization.js~DOMLocalization.html#instance-method-translateRoots",
    "src/dom_localization.js~DOMLocalization#translateRoots",
    "method"
  ],
  [
    "src/dom_localization.js~domlocalization#windowelement",
    "class/src/dom_localization.js~DOMLocalization.html#instance-member-windowElement",
    "src/dom_localization.js~DOMLocalization#windowElement",
    "member"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/localization.js",
    "file/src/localization.js.html",
    "src/localization.js",
    "file"
  ],
  [
    "src/localization.js~localization#addresourceids",
    "class/src/localization.js~Localization.html#instance-method-addResourceIds",
    "src/localization.js~Localization#addResourceIds",
    "method"
  ],
  [
    "src/localization.js~localization#bundles",
    "class/src/localization.js~Localization.html#instance-member-bundles",
    "src/localization.js~Localization#bundles",
    "member"
  ],
  [
    "src/localization.js~localization#constructor",
    "class/src/localization.js~Localization.html#instance-constructor-constructor",
    "src/localization.js~Localization#constructor",
    "method"
  ],
  [
    "src/localization.js~localization#formatmessages",
    "class/src/localization.js~Localization.html#instance-method-formatMessages",
    "src/localization.js~Localization#formatMessages",
    "method"
  ],
  [
    "src/localization.js~localization#formatvalue",
    "class/src/localization.js~Localization.html#instance-method-formatValue",
    "src/localization.js~Localization#formatValue",
    "method"
  ],
  [
    "src/localization.js~localization#formatvalues",
    "class/src/localization.js~Localization.html#instance-method-formatValues",
    "src/localization.js~Localization#formatValues",
    "method"
  ],
  [
    "src/localization.js~localization#formatwithfallback",
    "class/src/localization.js~Localization.html#instance-method-formatWithFallback",
    "src/localization.js~Localization#formatWithFallback",
    "method"
  ],
  [
    "src/localization.js~localization#generatebundles",
    "class/src/localization.js~Localization.html#instance-member-generateBundles",
    "src/localization.js~Localization#generateBundles",
    "member"
  ],
  [
    "src/localization.js~localization#handleevent",
    "class/src/localization.js~Localization.html#instance-method-handleEvent",
    "src/localization.js~Localization#handleEvent",
    "method"
  ],
  [
    "src/localization.js~localization#onchange",
    "class/src/localization.js~Localization.html#instance-method-onChange",
    "src/localization.js~Localization#onChange",
    "method"
  ],
  [
    "src/localization.js~localization#removeresourceids",
    "class/src/localization.js~Localization.html#instance-method-removeResourceIds",
    "src/localization.js~Localization#removeResourceIds",
    "method"
  ],
  [
    "src/localization.js~localization#resourceids",
    "class/src/localization.js~Localization.html#instance-member-resourceIds",
    "src/localization.js~Localization#resourceIds",
    "member"
  ],
  [
    "src/overlay.js",
    "file/src/overlay.js.html",
    "src/overlay.js",
    "file"
  ]
]