#!/bin/sh

hash gjslint &> /dev/null
if [ $? -eq 1 ];
then
  echo >&2 "You should install gjslint to lint your patch"
  echo >&2 "https://developers.google.com/closure/utilities/docs/linter_howto"
  exit 0
fi

gjslint --disable 1 --nojsdoc \
    -r bindings \
    -r lib \
    -x lib/l20n/intl.js
