window.esdocSearchIndex = [
  [
    "fluent/src/bundle.js~fluentbundle",
    "class/src/bundle.js~FluentBundle.html",
    "<span>FluentBundle</span> <span class=\"search-result-import-path\">fluent/src/bundle.js</span>",
    "class"
  ],
  [
    "fluent/src/types.js~fluentdatetime",
    "class/src/types.js~FluentDateTime.html",
    "<span>FluentDateTime</span> <span class=\"search-result-import-path\">fluent/src/types.js</span>",
    "class"
  ],
  [
    "fluent/src/error.js~fluenterror",
    "class/src/error.js~FluentError.html",
    "<span>FluentError</span> <span class=\"search-result-import-path\">fluent/src/error.js</span>",
    "class"
  ],
  [
    "fluent/src/types.js~fluentnone",
    "class/src/types.js~FluentNone.html",
    "<span>FluentNone</span> <span class=\"search-result-import-path\">fluent/src/types.js</span>",
    "class"
  ],
  [
    "fluent/src/types.js~fluentnumber",
    "class/src/types.js~FluentNumber.html",
    "<span>FluentNumber</span> <span class=\"search-result-import-path\">fluent/src/types.js</span>",
    "class"
  ],
  [
    "fluent/src/resource.js~fluentresource",
    "class/src/resource.js~FluentResource.html",
    "<span>FluentResource</span> <span class=\"search-result-import-path\">fluent/src/resource.js</span>",
    "class"
  ],
  [
    "fluent/src/types.js~fluenttype",
    "class/src/types.js~FluentType.html",
    "<span>FluentType</span> <span class=\"search-result-import-path\">fluent/src/types.js</span>",
    "class"
  ],
  [
    "fluent/src/util.js~ftl",
    "function/index.html#static-function-ftl",
    "<span>ftl</span> <span class=\"search-result-import-path\">fluent/src/util.js</span>",
    "function"
  ],
  [
    "fluent/src/resolver.js~resolve",
    "function/index.html#static-function-resolve",
    "<span>resolve</span> <span class=\"search-result-import-path\">fluent/src/resolver.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/builtins.js",
    "file/src/builtins.js.html",
    "src/builtins.js",
    "file"
  ],
  [
    "src/bundle.js",
    "file/src/bundle.js.html",
    "src/bundle.js",
    "file"
  ],
  [
    "src/bundle.js~fluentbundle#_functions",
    "class/src/bundle.js~FluentBundle.html#instance-member-_functions",
    "src/bundle.js~FluentBundle#_functions",
    "member"
  ],
  [
    "src/bundle.js~fluentbundle#_intls",
    "class/src/bundle.js~FluentBundle.html#instance-member-_intls",
    "src/bundle.js~FluentBundle#_intls",
    "member"
  ],
  [
    "src/bundle.js~fluentbundle#_memoizeintlobject",
    "class/src/bundle.js~FluentBundle.html#instance-method-_memoizeIntlObject",
    "src/bundle.js~FluentBundle#_memoizeIntlObject",
    "method"
  ],
  [
    "src/bundle.js~fluentbundle#_messages",
    "class/src/bundle.js~FluentBundle.html#instance-member-_messages",
    "src/bundle.js~FluentBundle#_messages",
    "member"
  ],
  [
    "src/bundle.js~fluentbundle#_terms",
    "class/src/bundle.js~FluentBundle.html#instance-member-_terms",
    "src/bundle.js~FluentBundle#_terms",
    "member"
  ],
  [
    "src/bundle.js~fluentbundle#_transform",
    "class/src/bundle.js~FluentBundle.html#instance-member-_transform",
    "src/bundle.js~FluentBundle#_transform",
    "member"
  ],
  [
    "src/bundle.js~fluentbundle#_useisolating",
    "class/src/bundle.js~FluentBundle.html#instance-member-_useIsolating",
    "src/bundle.js~FluentBundle#_useIsolating",
    "member"
  ],
  [
    "src/bundle.js~fluentbundle#addmessages",
    "class/src/bundle.js~FluentBundle.html#instance-method-addMessages",
    "src/bundle.js~FluentBundle#addMessages",
    "method"
  ],
  [
    "src/bundle.js~fluentbundle#addresource",
    "class/src/bundle.js~FluentBundle.html#instance-method-addResource",
    "src/bundle.js~FluentBundle#addResource",
    "method"
  ],
  [
    "src/bundle.js~fluentbundle#constructor",
    "class/src/bundle.js~FluentBundle.html#instance-constructor-constructor",
    "src/bundle.js~FluentBundle#constructor",
    "method"
  ],
  [
    "src/bundle.js~fluentbundle#format",
    "class/src/bundle.js~FluentBundle.html#instance-method-format",
    "src/bundle.js~FluentBundle#format",
    "method"
  ],
  [
    "src/bundle.js~fluentbundle#getmessage",
    "class/src/bundle.js~FluentBundle.html#instance-method-getMessage",
    "src/bundle.js~FluentBundle#getMessage",
    "method"
  ],
  [
    "src/bundle.js~fluentbundle#hasmessage",
    "class/src/bundle.js~FluentBundle.html#instance-method-hasMessage",
    "src/bundle.js~FluentBundle#hasMessage",
    "method"
  ],
  [
    "src/bundle.js~fluentbundle#locales",
    "class/src/bundle.js~FluentBundle.html#instance-member-locales",
    "src/bundle.js~FluentBundle#locales",
    "member"
  ],
  [
    "src/bundle.js~fluentbundle#messages",
    "class/src/bundle.js~FluentBundle.html#instance-get-messages",
    "src/bundle.js~FluentBundle#messages",
    "member"
  ],
  [
    "src/error.js",
    "file/src/error.js.html",
    "src/error.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/resolver.js",
    "file/src/resolver.js.html",
    "src/resolver.js",
    "file"
  ],
  [
    "src/resource.js",
    "file/src/resource.js.html",
    "src/resource.js",
    "file"
  ],
  [
    "src/resource.js~fluentresource.fromstring",
    "class/src/resource.js~FluentResource.html#static-method-fromString",
    "src/resource.js~FluentResource.fromString",
    "method"
  ],
  [
    "src/types.js",
    "file/src/types.js.html",
    "src/types.js",
    "file"
  ],
  [
    "src/types.js~fluentdatetime#constructor",
    "class/src/types.js~FluentDateTime.html#instance-constructor-constructor",
    "src/types.js~FluentDateTime#constructor",
    "method"
  ],
  [
    "src/types.js~fluentdatetime#tostring",
    "class/src/types.js~FluentDateTime.html#instance-method-toString",
    "src/types.js~FluentDateTime#toString",
    "method"
  ],
  [
    "src/types.js~fluentnone#tostring",
    "class/src/types.js~FluentNone.html#instance-method-toString",
    "src/types.js~FluentNone#toString",
    "method"
  ],
  [
    "src/types.js~fluentnumber#constructor",
    "class/src/types.js~FluentNumber.html#instance-constructor-constructor",
    "src/types.js~FluentNumber#constructor",
    "method"
  ],
  [
    "src/types.js~fluentnumber#tostring",
    "class/src/types.js~FluentNumber.html#instance-method-toString",
    "src/types.js~FluentNumber#toString",
    "method"
  ],
  [
    "src/types.js~fluenttype#constructor",
    "class/src/types.js~FluentType.html#instance-constructor-constructor",
    "src/types.js~FluentType#constructor",
    "method"
  ],
  [
    "src/types.js~fluenttype#opts",
    "class/src/types.js~FluentType.html#instance-member-opts",
    "src/types.js~FluentType#opts",
    "member"
  ],
  [
    "src/types.js~fluenttype#tostring",
    "class/src/types.js~FluentType.html#instance-method-toString",
    "src/types.js~FluentType#toString",
    "method"
  ],
  [
    "src/types.js~fluenttype#value",
    "class/src/types.js~FluentType.html#instance-member-value",
    "src/types.js~FluentType#value",
    "member"
  ],
  [
    "src/types.js~fluenttype#valueof",
    "class/src/types.js~FluentType.html#instance-method-valueOf",
    "src/types.js~FluentType#valueOf",
    "method"
  ],
  [
    "src/util.js",
    "file/src/util.js.html",
    "src/util.js",
    "file"
  ]
]