window.esdocSearchIndex = [
  [
    "fluent-syntax/src/ast.js~annotation",
    "class/src/ast.js~Annotation.html",
    "<span>Annotation</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~attribute",
    "class/src/ast.js~Attribute.html",
    "<span>Attribute</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~basecomment",
    "class/src/ast.js~BaseComment.html",
    "<span>BaseComment</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~basenode",
    "class/src/ast.js~BaseNode.html",
    "<span>BaseNode</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~callarguments",
    "class/src/ast.js~CallArguments.html",
    "<span>CallArguments</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~comment",
    "class/src/ast.js~Comment.html",
    "<span>Comment</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/stream.js~eof",
    "variable/index.html#static-variable-EOF",
    "<span>EOF</span> <span class=\"search-result-import-path\">fluent-syntax/src/stream.js</span>",
    "variable"
  ],
  [
    "fluent-syntax/src/stream.js~eol",
    "variable/index.html#static-variable-EOL",
    "<span>EOL</span> <span class=\"search-result-import-path\">fluent-syntax/src/stream.js</span>",
    "variable"
  ],
  [
    "fluent-syntax/src/ast.js~entry",
    "class/src/ast.js~Entry.html",
    "<span>Entry</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~expression",
    "class/src/ast.js~Expression.html",
    "<span>Expression</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/parser.js~fluentparser",
    "class/src/parser.js~FluentParser.html",
    "<span>FluentParser</span> <span class=\"search-result-import-path\">fluent-syntax/src/parser.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/stream.js~fluentparserstream",
    "class/src/stream.js~FluentParserStream.html",
    "<span>FluentParserStream</span> <span class=\"search-result-import-path\">fluent-syntax/src/stream.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/serializer.js~fluentserializer",
    "class/src/serializer.js~FluentSerializer.html",
    "<span>FluentSerializer</span> <span class=\"search-result-import-path\">fluent-syntax/src/serializer.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~functionreference",
    "class/src/ast.js~FunctionReference.html",
    "<span>FunctionReference</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~groupcomment",
    "class/src/ast.js~GroupComment.html",
    "<span>GroupComment</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/serializer.js~has_entries",
    "variable/index.html#static-variable-HAS_ENTRIES",
    "<span>HAS_ENTRIES</span> <span class=\"search-result-import-path\">fluent-syntax/src/serializer.js</span>",
    "variable"
  ],
  [
    "fluent-syntax/src/ast.js~identifier",
    "class/src/ast.js~Identifier.html",
    "<span>Identifier</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~junk",
    "class/src/ast.js~Junk.html",
    "<span>Junk</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~literal",
    "class/src/ast.js~Literal.html",
    "<span>Literal</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~message",
    "class/src/ast.js~Message.html",
    "<span>Message</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~messagereference",
    "class/src/ast.js~MessageReference.html",
    "<span>MessageReference</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~namedargument",
    "class/src/ast.js~NamedArgument.html",
    "<span>NamedArgument</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~numberliteral",
    "class/src/ast.js~NumberLiteral.html",
    "<span>NumberLiteral</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/errors.js~parseerror",
    "class/src/errors.js~ParseError.html",
    "<span>ParseError</span> <span class=\"search-result-import-path\">fluent-syntax/src/errors.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/stream.js~parserstream",
    "class/src/stream.js~ParserStream.html",
    "<span>ParserStream</span> <span class=\"search-result-import-path\">fluent-syntax/src/stream.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~pattern",
    "class/src/ast.js~Pattern.html",
    "<span>Pattern</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~patternelement",
    "class/src/ast.js~PatternElement.html",
    "<span>PatternElement</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~placeable",
    "class/src/ast.js~Placeable.html",
    "<span>Placeable</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~resource",
    "class/src/ast.js~Resource.html",
    "<span>Resource</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~resourcecomment",
    "class/src/ast.js~ResourceComment.html",
    "<span>ResourceComment</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~selectexpression",
    "class/src/ast.js~SelectExpression.html",
    "<span>SelectExpression</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~span",
    "class/src/ast.js~Span.html",
    "<span>Span</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~stringliteral",
    "class/src/ast.js~StringLiteral.html",
    "<span>StringLiteral</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~syntaxnode",
    "class/src/ast.js~SyntaxNode.html",
    "<span>SyntaxNode</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~term",
    "class/src/ast.js~Term.html",
    "<span>Term</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~termreference",
    "class/src/ast.js~TermReference.html",
    "<span>TermReference</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~textelement",
    "class/src/ast.js~TextElement.html",
    "<span>TextElement</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/visitor.js~transformer",
    "class/src/visitor.js~Transformer.html",
    "<span>Transformer</span> <span class=\"search-result-import-path\">fluent-syntax/src/visitor.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~variablereference",
    "class/src/ast.js~VariableReference.html",
    "<span>VariableReference</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/ast.js~variant",
    "class/src/ast.js~Variant.html",
    "<span>Variant</span> <span class=\"search-result-import-path\">fluent-syntax/src/ast.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/visitor.js~visitor",
    "class/src/visitor.js~Visitor.html",
    "<span>Visitor</span> <span class=\"search-result-import-path\">fluent-syntax/src/visitor.js</span>",
    "class"
  ],
  [
    "fluent-syntax/src/index.js~columnoffset",
    "function/index.html#static-function-columnOffset",
    "<span>columnOffset</span> <span class=\"search-result-import-path\">fluent-syntax/src/index.js</span>",
    "function"
  ],
  [
    "fluent-syntax/src/util.js~includes",
    "function/index.html#static-function-includes",
    "<span>includes</span> <span class=\"search-result-import-path\">fluent-syntax/src/util.js</span>",
    "function"
  ],
  [
    "fluent-syntax/src/index.js~lineoffset",
    "function/index.html#static-function-lineOffset",
    "<span>lineOffset</span> <span class=\"search-result-import-path\">fluent-syntax/src/index.js</span>",
    "function"
  ],
  [
    "fluent-syntax/src/index.js~parse",
    "function/index.html#static-function-parse",
    "<span>parse</span> <span class=\"search-result-import-path\">fluent-syntax/src/index.js</span>",
    "function"
  ],
  [
    "fluent-syntax/src/index.js~serialize",
    "function/index.html#static-function-serialize",
    "<span>serialize</span> <span class=\"search-result-import-path\">fluent-syntax/src/index.js</span>",
    "function"
  ],
  [
    "fluent-syntax/src/serializer.js~serializeexpression",
    "function/index.html#static-function-serializeExpression",
    "<span>serializeExpression</span> <span class=\"search-result-import-path\">fluent-syntax/src/serializer.js</span>",
    "function"
  ],
  [
    "fluent-syntax/src/serializer.js~serializevariantkey",
    "function/index.html#static-function-serializeVariantKey",
    "<span>serializeVariantKey</span> <span class=\"search-result-import-path\">fluent-syntax/src/serializer.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/ast.js",
    "file/src/ast.js.html",
    "src/ast.js",
    "file"
  ],
  [
    "src/ast.js~annotation#arguments",
    "class/src/ast.js~Annotation.html#instance-member-arguments",
    "src/ast.js~Annotation#arguments",
    "member"
  ],
  [
    "src/ast.js~annotation#code",
    "class/src/ast.js~Annotation.html#instance-member-code",
    "src/ast.js~Annotation#code",
    "member"
  ],
  [
    "src/ast.js~annotation#constructor",
    "class/src/ast.js~Annotation.html#instance-constructor-constructor",
    "src/ast.js~Annotation#constructor",
    "method"
  ],
  [
    "src/ast.js~annotation#message",
    "class/src/ast.js~Annotation.html#instance-member-message",
    "src/ast.js~Annotation#message",
    "member"
  ],
  [
    "src/ast.js~annotation#type",
    "class/src/ast.js~Annotation.html#instance-member-type",
    "src/ast.js~Annotation#type",
    "member"
  ],
  [
    "src/ast.js~attribute#constructor",
    "class/src/ast.js~Attribute.html#instance-constructor-constructor",
    "src/ast.js~Attribute#constructor",
    "method"
  ],
  [
    "src/ast.js~attribute#id",
    "class/src/ast.js~Attribute.html#instance-member-id",
    "src/ast.js~Attribute#id",
    "member"
  ],
  [
    "src/ast.js~attribute#type",
    "class/src/ast.js~Attribute.html#instance-member-type",
    "src/ast.js~Attribute#type",
    "member"
  ],
  [
    "src/ast.js~attribute#value",
    "class/src/ast.js~Attribute.html#instance-member-value",
    "src/ast.js~Attribute#value",
    "member"
  ],
  [
    "src/ast.js~basecomment#constructor",
    "class/src/ast.js~BaseComment.html#instance-constructor-constructor",
    "src/ast.js~BaseComment#constructor",
    "method"
  ],
  [
    "src/ast.js~basecomment#content",
    "class/src/ast.js~BaseComment.html#instance-member-content",
    "src/ast.js~BaseComment#content",
    "member"
  ],
  [
    "src/ast.js~basecomment#type",
    "class/src/ast.js~BaseComment.html#instance-member-type",
    "src/ast.js~BaseComment#type",
    "member"
  ],
  [
    "src/ast.js~basenode#clone",
    "class/src/ast.js~BaseNode.html#instance-method-clone",
    "src/ast.js~BaseNode#clone",
    "method"
  ],
  [
    "src/ast.js~basenode#constructor",
    "class/src/ast.js~BaseNode.html#instance-constructor-constructor",
    "src/ast.js~BaseNode#constructor",
    "method"
  ],
  [
    "src/ast.js~basenode#equals",
    "class/src/ast.js~BaseNode.html#instance-method-equals",
    "src/ast.js~BaseNode#equals",
    "method"
  ],
  [
    "src/ast.js~callarguments#constructor",
    "class/src/ast.js~CallArguments.html#instance-constructor-constructor",
    "src/ast.js~CallArguments#constructor",
    "method"
  ],
  [
    "src/ast.js~callarguments#named",
    "class/src/ast.js~CallArguments.html#instance-member-named",
    "src/ast.js~CallArguments#named",
    "member"
  ],
  [
    "src/ast.js~callarguments#positional",
    "class/src/ast.js~CallArguments.html#instance-member-positional",
    "src/ast.js~CallArguments#positional",
    "member"
  ],
  [
    "src/ast.js~callarguments#type",
    "class/src/ast.js~CallArguments.html#instance-member-type",
    "src/ast.js~CallArguments#type",
    "member"
  ],
  [
    "src/ast.js~comment#constructor",
    "class/src/ast.js~Comment.html#instance-constructor-constructor",
    "src/ast.js~Comment#constructor",
    "method"
  ],
  [
    "src/ast.js~comment#type",
    "class/src/ast.js~Comment.html#instance-member-type",
    "src/ast.js~Comment#type",
    "member"
  ],
  [
    "src/ast.js~functionreference#arguments",
    "class/src/ast.js~FunctionReference.html#instance-member-arguments",
    "src/ast.js~FunctionReference#arguments",
    "member"
  ],
  [
    "src/ast.js~functionreference#constructor",
    "class/src/ast.js~FunctionReference.html#instance-constructor-constructor",
    "src/ast.js~FunctionReference#constructor",
    "method"
  ],
  [
    "src/ast.js~functionreference#id",
    "class/src/ast.js~FunctionReference.html#instance-member-id",
    "src/ast.js~FunctionReference#id",
    "member"
  ],
  [
    "src/ast.js~functionreference#type",
    "class/src/ast.js~FunctionReference.html#instance-member-type",
    "src/ast.js~FunctionReference#type",
    "member"
  ],
  [
    "src/ast.js~groupcomment#constructor",
    "class/src/ast.js~GroupComment.html#instance-constructor-constructor",
    "src/ast.js~GroupComment#constructor",
    "method"
  ],
  [
    "src/ast.js~groupcomment#type",
    "class/src/ast.js~GroupComment.html#instance-member-type",
    "src/ast.js~GroupComment#type",
    "member"
  ],
  [
    "src/ast.js~identifier#constructor",
    "class/src/ast.js~Identifier.html#instance-constructor-constructor",
    "src/ast.js~Identifier#constructor",
    "method"
  ],
  [
    "src/ast.js~identifier#name",
    "class/src/ast.js~Identifier.html#instance-member-name",
    "src/ast.js~Identifier#name",
    "member"
  ],
  [
    "src/ast.js~identifier#type",
    "class/src/ast.js~Identifier.html#instance-member-type",
    "src/ast.js~Identifier#type",
    "member"
  ],
  [
    "src/ast.js~junk#addannotation",
    "class/src/ast.js~Junk.html#instance-method-addAnnotation",
    "src/ast.js~Junk#addAnnotation",
    "method"
  ],
  [
    "src/ast.js~junk#annotations",
    "class/src/ast.js~Junk.html#instance-member-annotations",
    "src/ast.js~Junk#annotations",
    "member"
  ],
  [
    "src/ast.js~junk#constructor",
    "class/src/ast.js~Junk.html#instance-constructor-constructor",
    "src/ast.js~Junk#constructor",
    "method"
  ],
  [
    "src/ast.js~junk#content",
    "class/src/ast.js~Junk.html#instance-member-content",
    "src/ast.js~Junk#content",
    "member"
  ],
  [
    "src/ast.js~junk#type",
    "class/src/ast.js~Junk.html#instance-member-type",
    "src/ast.js~Junk#type",
    "member"
  ],
  [
    "src/ast.js~literal#constructor",
    "class/src/ast.js~Literal.html#instance-constructor-constructor",
    "src/ast.js~Literal#constructor",
    "method"
  ],
  [
    "src/ast.js~literal#parse",
    "class/src/ast.js~Literal.html#instance-method-parse",
    "src/ast.js~Literal#parse",
    "method"
  ],
  [
    "src/ast.js~literal#value",
    "class/src/ast.js~Literal.html#instance-member-value",
    "src/ast.js~Literal#value",
    "member"
  ],
  [
    "src/ast.js~message#attributes",
    "class/src/ast.js~Message.html#instance-member-attributes",
    "src/ast.js~Message#attributes",
    "member"
  ],
  [
    "src/ast.js~message#comment",
    "class/src/ast.js~Message.html#instance-member-comment",
    "src/ast.js~Message#comment",
    "member"
  ],
  [
    "src/ast.js~message#constructor",
    "class/src/ast.js~Message.html#instance-constructor-constructor",
    "src/ast.js~Message#constructor",
    "method"
  ],
  [
    "src/ast.js~message#id",
    "class/src/ast.js~Message.html#instance-member-id",
    "src/ast.js~Message#id",
    "member"
  ],
  [
    "src/ast.js~message#type",
    "class/src/ast.js~Message.html#instance-member-type",
    "src/ast.js~Message#type",
    "member"
  ],
  [
    "src/ast.js~message#value",
    "class/src/ast.js~Message.html#instance-member-value",
    "src/ast.js~Message#value",
    "member"
  ],
  [
    "src/ast.js~messagereference#attribute",
    "class/src/ast.js~MessageReference.html#instance-member-attribute",
    "src/ast.js~MessageReference#attribute",
    "member"
  ],
  [
    "src/ast.js~messagereference#constructor",
    "class/src/ast.js~MessageReference.html#instance-constructor-constructor",
    "src/ast.js~MessageReference#constructor",
    "method"
  ],
  [
    "src/ast.js~messagereference#id",
    "class/src/ast.js~MessageReference.html#instance-member-id",
    "src/ast.js~MessageReference#id",
    "member"
  ],
  [
    "src/ast.js~messagereference#type",
    "class/src/ast.js~MessageReference.html#instance-member-type",
    "src/ast.js~MessageReference#type",
    "member"
  ],
  [
    "src/ast.js~namedargument#constructor",
    "class/src/ast.js~NamedArgument.html#instance-constructor-constructor",
    "src/ast.js~NamedArgument#constructor",
    "method"
  ],
  [
    "src/ast.js~namedargument#name",
    "class/src/ast.js~NamedArgument.html#instance-member-name",
    "src/ast.js~NamedArgument#name",
    "member"
  ],
  [
    "src/ast.js~namedargument#type",
    "class/src/ast.js~NamedArgument.html#instance-member-type",
    "src/ast.js~NamedArgument#type",
    "member"
  ],
  [
    "src/ast.js~namedargument#value",
    "class/src/ast.js~NamedArgument.html#instance-member-value",
    "src/ast.js~NamedArgument#value",
    "member"
  ],
  [
    "src/ast.js~numberliteral#constructor",
    "class/src/ast.js~NumberLiteral.html#instance-constructor-constructor",
    "src/ast.js~NumberLiteral#constructor",
    "method"
  ],
  [
    "src/ast.js~numberliteral#parse",
    "class/src/ast.js~NumberLiteral.html#instance-method-parse",
    "src/ast.js~NumberLiteral#parse",
    "method"
  ],
  [
    "src/ast.js~numberliteral#type",
    "class/src/ast.js~NumberLiteral.html#instance-member-type",
    "src/ast.js~NumberLiteral#type",
    "member"
  ],
  [
    "src/ast.js~pattern#constructor",
    "class/src/ast.js~Pattern.html#instance-constructor-constructor",
    "src/ast.js~Pattern#constructor",
    "method"
  ],
  [
    "src/ast.js~pattern#elements",
    "class/src/ast.js~Pattern.html#instance-member-elements",
    "src/ast.js~Pattern#elements",
    "member"
  ],
  [
    "src/ast.js~pattern#type",
    "class/src/ast.js~Pattern.html#instance-member-type",
    "src/ast.js~Pattern#type",
    "member"
  ],
  [
    "src/ast.js~placeable#constructor",
    "class/src/ast.js~Placeable.html#instance-constructor-constructor",
    "src/ast.js~Placeable#constructor",
    "method"
  ],
  [
    "src/ast.js~placeable#expression",
    "class/src/ast.js~Placeable.html#instance-member-expression",
    "src/ast.js~Placeable#expression",
    "member"
  ],
  [
    "src/ast.js~placeable#type",
    "class/src/ast.js~Placeable.html#instance-member-type",
    "src/ast.js~Placeable#type",
    "member"
  ],
  [
    "src/ast.js~resource#body",
    "class/src/ast.js~Resource.html#instance-member-body",
    "src/ast.js~Resource#body",
    "member"
  ],
  [
    "src/ast.js~resource#constructor",
    "class/src/ast.js~Resource.html#instance-constructor-constructor",
    "src/ast.js~Resource#constructor",
    "method"
  ],
  [
    "src/ast.js~resource#type",
    "class/src/ast.js~Resource.html#instance-member-type",
    "src/ast.js~Resource#type",
    "member"
  ],
  [
    "src/ast.js~resourcecomment#constructor",
    "class/src/ast.js~ResourceComment.html#instance-constructor-constructor",
    "src/ast.js~ResourceComment#constructor",
    "method"
  ],
  [
    "src/ast.js~resourcecomment#type",
    "class/src/ast.js~ResourceComment.html#instance-member-type",
    "src/ast.js~ResourceComment#type",
    "member"
  ],
  [
    "src/ast.js~selectexpression#constructor",
    "class/src/ast.js~SelectExpression.html#instance-constructor-constructor",
    "src/ast.js~SelectExpression#constructor",
    "method"
  ],
  [
    "src/ast.js~selectexpression#selector",
    "class/src/ast.js~SelectExpression.html#instance-member-selector",
    "src/ast.js~SelectExpression#selector",
    "member"
  ],
  [
    "src/ast.js~selectexpression#type",
    "class/src/ast.js~SelectExpression.html#instance-member-type",
    "src/ast.js~SelectExpression#type",
    "member"
  ],
  [
    "src/ast.js~selectexpression#variants",
    "class/src/ast.js~SelectExpression.html#instance-member-variants",
    "src/ast.js~SelectExpression#variants",
    "member"
  ],
  [
    "src/ast.js~span#constructor",
    "class/src/ast.js~Span.html#instance-constructor-constructor",
    "src/ast.js~Span#constructor",
    "method"
  ],
  [
    "src/ast.js~span#end",
    "class/src/ast.js~Span.html#instance-member-end",
    "src/ast.js~Span#end",
    "member"
  ],
  [
    "src/ast.js~span#start",
    "class/src/ast.js~Span.html#instance-member-start",
    "src/ast.js~Span#start",
    "member"
  ],
  [
    "src/ast.js~span#type",
    "class/src/ast.js~Span.html#instance-member-type",
    "src/ast.js~Span#type",
    "member"
  ],
  [
    "src/ast.js~stringliteral#constructor",
    "class/src/ast.js~StringLiteral.html#instance-constructor-constructor",
    "src/ast.js~StringLiteral#constructor",
    "method"
  ],
  [
    "src/ast.js~stringliteral#parse",
    "class/src/ast.js~StringLiteral.html#instance-method-parse",
    "src/ast.js~StringLiteral#parse",
    "method"
  ],
  [
    "src/ast.js~stringliteral#type",
    "class/src/ast.js~StringLiteral.html#instance-member-type",
    "src/ast.js~StringLiteral#type",
    "member"
  ],
  [
    "src/ast.js~syntaxnode#addspan",
    "class/src/ast.js~SyntaxNode.html#instance-method-addSpan",
    "src/ast.js~SyntaxNode#addSpan",
    "method"
  ],
  [
    "src/ast.js~syntaxnode#span",
    "class/src/ast.js~SyntaxNode.html#instance-member-span",
    "src/ast.js~SyntaxNode#span",
    "member"
  ],
  [
    "src/ast.js~term#attributes",
    "class/src/ast.js~Term.html#instance-member-attributes",
    "src/ast.js~Term#attributes",
    "member"
  ],
  [
    "src/ast.js~term#comment",
    "class/src/ast.js~Term.html#instance-member-comment",
    "src/ast.js~Term#comment",
    "member"
  ],
  [
    "src/ast.js~term#constructor",
    "class/src/ast.js~Term.html#instance-constructor-constructor",
    "src/ast.js~Term#constructor",
    "method"
  ],
  [
    "src/ast.js~term#id",
    "class/src/ast.js~Term.html#instance-member-id",
    "src/ast.js~Term#id",
    "member"
  ],
  [
    "src/ast.js~term#type",
    "class/src/ast.js~Term.html#instance-member-type",
    "src/ast.js~Term#type",
    "member"
  ],
  [
    "src/ast.js~term#value",
    "class/src/ast.js~Term.html#instance-member-value",
    "src/ast.js~Term#value",
    "member"
  ],
  [
    "src/ast.js~termreference#arguments",
    "class/src/ast.js~TermReference.html#instance-member-arguments",
    "src/ast.js~TermReference#arguments",
    "member"
  ],
  [
    "src/ast.js~termreference#attribute",
    "class/src/ast.js~TermReference.html#instance-member-attribute",
    "src/ast.js~TermReference#attribute",
    "member"
  ],
  [
    "src/ast.js~termreference#constructor",
    "class/src/ast.js~TermReference.html#instance-constructor-constructor",
    "src/ast.js~TermReference#constructor",
    "method"
  ],
  [
    "src/ast.js~termreference#id",
    "class/src/ast.js~TermReference.html#instance-member-id",
    "src/ast.js~TermReference#id",
    "member"
  ],
  [
    "src/ast.js~termreference#type",
    "class/src/ast.js~TermReference.html#instance-member-type",
    "src/ast.js~TermReference#type",
    "member"
  ],
  [
    "src/ast.js~textelement#constructor",
    "class/src/ast.js~TextElement.html#instance-constructor-constructor",
    "src/ast.js~TextElement#constructor",
    "method"
  ],
  [
    "src/ast.js~textelement#type",
    "class/src/ast.js~TextElement.html#instance-member-type",
    "src/ast.js~TextElement#type",
    "member"
  ],
  [
    "src/ast.js~textelement#value",
    "class/src/ast.js~TextElement.html#instance-member-value",
    "src/ast.js~TextElement#value",
    "member"
  ],
  [
    "src/ast.js~variablereference#constructor",
    "class/src/ast.js~VariableReference.html#instance-constructor-constructor",
    "src/ast.js~VariableReference#constructor",
    "method"
  ],
  [
    "src/ast.js~variablereference#id",
    "class/src/ast.js~VariableReference.html#instance-member-id",
    "src/ast.js~VariableReference#id",
    "member"
  ],
  [
    "src/ast.js~variablereference#type",
    "class/src/ast.js~VariableReference.html#instance-member-type",
    "src/ast.js~VariableReference#type",
    "member"
  ],
  [
    "src/ast.js~variant#constructor",
    "class/src/ast.js~Variant.html#instance-constructor-constructor",
    "src/ast.js~Variant#constructor",
    "method"
  ],
  [
    "src/ast.js~variant#default",
    "class/src/ast.js~Variant.html#instance-member-default",
    "src/ast.js~Variant#default",
    "member"
  ],
  [
    "src/ast.js~variant#key",
    "class/src/ast.js~Variant.html#instance-member-key",
    "src/ast.js~Variant#key",
    "member"
  ],
  [
    "src/ast.js~variant#type",
    "class/src/ast.js~Variant.html#instance-member-type",
    "src/ast.js~Variant#type",
    "member"
  ],
  [
    "src/ast.js~variant#value",
    "class/src/ast.js~Variant.html#instance-member-value",
    "src/ast.js~Variant#value",
    "member"
  ],
  [
    "src/errors.js",
    "file/src/errors.js.html",
    "src/errors.js",
    "file"
  ],
  [
    "src/errors.js~parseerror#args",
    "class/src/errors.js~ParseError.html#instance-member-args",
    "src/errors.js~ParseError#args",
    "member"
  ],
  [
    "src/errors.js~parseerror#code",
    "class/src/errors.js~ParseError.html#instance-member-code",
    "src/errors.js~ParseError#code",
    "member"
  ],
  [
    "src/errors.js~parseerror#constructor",
    "class/src/errors.js~ParseError.html#instance-constructor-constructor",
    "src/errors.js~ParseError#constructor",
    "method"
  ],
  [
    "src/errors.js~parseerror#message",
    "class/src/errors.js~ParseError.html#instance-member-message",
    "src/errors.js~ParseError#message",
    "member"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/parser.js",
    "file/src/parser.js.html",
    "src/parser.js",
    "file"
  ],
  [
    "src/parser.js~fluentparser#[name]",
    "class/src/parser.js~FluentParser.html#instance-member-[name]",
    "src/parser.js~FluentParser#[name]",
    "member"
  ],
  [
    "src/parser.js~fluentparser#constructor",
    "class/src/parser.js~FluentParser.html#instance-constructor-constructor",
    "src/parser.js~FluentParser#constructor",
    "method"
  ],
  [
    "src/parser.js~fluentparser#dedent",
    "class/src/parser.js~FluentParser.html#instance-method-dedent",
    "src/parser.js~FluentParser#dedent",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getattribute",
    "class/src/parser.js~FluentParser.html#instance-method-getAttribute",
    "src/parser.js~FluentParser#getAttribute",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getattributes",
    "class/src/parser.js~FluentParser.html#instance-method-getAttributes",
    "src/parser.js~FluentParser#getAttributes",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getcallargument",
    "class/src/parser.js~FluentParser.html#instance-method-getCallArgument",
    "src/parser.js~FluentParser#getCallArgument",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getcallarguments",
    "class/src/parser.js~FluentParser.html#instance-method-getCallArguments",
    "src/parser.js~FluentParser#getCallArguments",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getcomment",
    "class/src/parser.js~FluentParser.html#instance-method-getComment",
    "src/parser.js~FluentParser#getComment",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getdigits",
    "class/src/parser.js~FluentParser.html#instance-method-getDigits",
    "src/parser.js~FluentParser#getDigits",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getentry",
    "class/src/parser.js~FluentParser.html#instance-method-getEntry",
    "src/parser.js~FluentParser#getEntry",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getentryorjunk",
    "class/src/parser.js~FluentParser.html#instance-method-getEntryOrJunk",
    "src/parser.js~FluentParser#getEntryOrJunk",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getescapesequence",
    "class/src/parser.js~FluentParser.html#instance-method-getEscapeSequence",
    "src/parser.js~FluentParser#getEscapeSequence",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getexpression",
    "class/src/parser.js~FluentParser.html#instance-method-getExpression",
    "src/parser.js~FluentParser#getExpression",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getidentifier",
    "class/src/parser.js~FluentParser.html#instance-method-getIdentifier",
    "src/parser.js~FluentParser#getIdentifier",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getindent",
    "class/src/parser.js~FluentParser.html#instance-method-getIndent",
    "src/parser.js~FluentParser#getIndent",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getinlineexpression",
    "class/src/parser.js~FluentParser.html#instance-method-getInlineExpression",
    "src/parser.js~FluentParser#getInlineExpression",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getliteral",
    "class/src/parser.js~FluentParser.html#instance-method-getLiteral",
    "src/parser.js~FluentParser#getLiteral",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getmessage",
    "class/src/parser.js~FluentParser.html#instance-method-getMessage",
    "src/parser.js~FluentParser#getMessage",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getnumber",
    "class/src/parser.js~FluentParser.html#instance-method-getNumber",
    "src/parser.js~FluentParser#getNumber",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getpattern",
    "class/src/parser.js~FluentParser.html#instance-method-getPattern",
    "src/parser.js~FluentParser#getPattern",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getplaceable",
    "class/src/parser.js~FluentParser.html#instance-method-getPlaceable",
    "src/parser.js~FluentParser#getPlaceable",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getstring",
    "class/src/parser.js~FluentParser.html#instance-method-getString",
    "src/parser.js~FluentParser#getString",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getterm",
    "class/src/parser.js~FluentParser.html#instance-method-getTerm",
    "src/parser.js~FluentParser#getTerm",
    "method"
  ],
  [
    "src/parser.js~fluentparser#gettextelement",
    "class/src/parser.js~FluentParser.html#instance-method-getTextElement",
    "src/parser.js~FluentParser#getTextElement",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getunicodeescapesequence",
    "class/src/parser.js~FluentParser.html#instance-method-getUnicodeEscapeSequence",
    "src/parser.js~FluentParser#getUnicodeEscapeSequence",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getvariant",
    "class/src/parser.js~FluentParser.html#instance-method-getVariant",
    "src/parser.js~FluentParser#getVariant",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getvariantkey",
    "class/src/parser.js~FluentParser.html#instance-method-getVariantKey",
    "src/parser.js~FluentParser#getVariantKey",
    "method"
  ],
  [
    "src/parser.js~fluentparser#getvariants",
    "class/src/parser.js~FluentParser.html#instance-method-getVariants",
    "src/parser.js~FluentParser#getVariants",
    "method"
  ],
  [
    "src/parser.js~fluentparser#maybegetpattern",
    "class/src/parser.js~FluentParser.html#instance-method-maybeGetPattern",
    "src/parser.js~FluentParser#maybeGetPattern",
    "method"
  ],
  [
    "src/parser.js~fluentparser#parse",
    "class/src/parser.js~FluentParser.html#instance-method-parse",
    "src/parser.js~FluentParser#parse",
    "method"
  ],
  [
    "src/parser.js~fluentparser#parseentry",
    "class/src/parser.js~FluentParser.html#instance-method-parseEntry",
    "src/parser.js~FluentParser#parseEntry",
    "method"
  ],
  [
    "src/parser.js~fluentparser#withspans",
    "class/src/parser.js~FluentParser.html#instance-member-withSpans",
    "src/parser.js~FluentParser#withSpans",
    "member"
  ],
  [
    "src/serializer.js",
    "file/src/serializer.js.html",
    "src/serializer.js",
    "file"
  ],
  [
    "src/serializer.js~fluentserializer#constructor",
    "class/src/serializer.js~FluentSerializer.html#instance-constructor-constructor",
    "src/serializer.js~FluentSerializer#constructor",
    "method"
  ],
  [
    "src/serializer.js~fluentserializer#serialize",
    "class/src/serializer.js~FluentSerializer.html#instance-method-serialize",
    "src/serializer.js~FluentSerializer#serialize",
    "method"
  ],
  [
    "src/serializer.js~fluentserializer#serializeentry",
    "class/src/serializer.js~FluentSerializer.html#instance-method-serializeEntry",
    "src/serializer.js~FluentSerializer#serializeEntry",
    "method"
  ],
  [
    "src/serializer.js~fluentserializer#withjunk",
    "class/src/serializer.js~FluentSerializer.html#instance-member-withJunk",
    "src/serializer.js~FluentSerializer#withJunk",
    "member"
  ],
  [
    "src/stream.js",
    "file/src/stream.js.html",
    "src/stream.js",
    "file"
  ],
  [
    "src/stream.js~fluentparserstream#expectchar",
    "class/src/stream.js~FluentParserStream.html#instance-method-expectChar",
    "src/stream.js~FluentParserStream#expectChar",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#expectlineend",
    "class/src/stream.js~FluentParserStream.html#instance-method-expectLineEnd",
    "src/stream.js~FluentParserStream#expectLineEnd",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#index",
    "class/src/stream.js~FluentParserStream.html#instance-member-index",
    "src/stream.js~FluentParserStream#index",
    "member"
  ],
  [
    "src/stream.js~fluentparserstream#isattributestart",
    "class/src/stream.js~FluentParserStream.html#instance-method-isAttributeStart",
    "src/stream.js~FluentParserStream#isAttributeStart",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#ischaridstart",
    "class/src/stream.js~FluentParserStream.html#instance-method-isCharIdStart",
    "src/stream.js~FluentParserStream#isCharIdStart",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#ischarpatterncontinuation",
    "class/src/stream.js~FluentParserStream.html#instance-method-isCharPatternContinuation",
    "src/stream.js~FluentParserStream#isCharPatternContinuation",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#isidentifierstart",
    "class/src/stream.js~FluentParserStream.html#instance-method-isIdentifierStart",
    "src/stream.js~FluentParserStream#isIdentifierStart",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#isnextlinecomment",
    "class/src/stream.js~FluentParserStream.html#instance-method-isNextLineComment",
    "src/stream.js~FluentParserStream#isNextLineComment",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#isnumberstart",
    "class/src/stream.js~FluentParserStream.html#instance-method-isNumberStart",
    "src/stream.js~FluentParserStream#isNumberStart",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#isvaluecontinuation",
    "class/src/stream.js~FluentParserStream.html#instance-method-isValueContinuation",
    "src/stream.js~FluentParserStream#isValueContinuation",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#isvaluestart",
    "class/src/stream.js~FluentParserStream.html#instance-method-isValueStart",
    "src/stream.js~FluentParserStream#isValueStart",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#isvariantstart",
    "class/src/stream.js~FluentParserStream.html#instance-method-isVariantStart",
    "src/stream.js~FluentParserStream#isVariantStart",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#peekblank",
    "class/src/stream.js~FluentParserStream.html#instance-method-peekBlank",
    "src/stream.js~FluentParserStream#peekBlank",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#peekblankblock",
    "class/src/stream.js~FluentParserStream.html#instance-method-peekBlankBlock",
    "src/stream.js~FluentParserStream#peekBlankBlock",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#peekblankinline",
    "class/src/stream.js~FluentParserStream.html#instance-method-peekBlankInline",
    "src/stream.js~FluentParserStream#peekBlankInline",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#skipblank",
    "class/src/stream.js~FluentParserStream.html#instance-method-skipBlank",
    "src/stream.js~FluentParserStream#skipBlank",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#skipblankblock",
    "class/src/stream.js~FluentParserStream.html#instance-method-skipBlankBlock",
    "src/stream.js~FluentParserStream#skipBlankBlock",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#skipblankinline",
    "class/src/stream.js~FluentParserStream.html#instance-method-skipBlankInline",
    "src/stream.js~FluentParserStream#skipBlankInline",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#skiptonextentrystart",
    "class/src/stream.js~FluentParserStream.html#instance-method-skipToNextEntryStart",
    "src/stream.js~FluentParserStream#skipToNextEntryStart",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#takechar",
    "class/src/stream.js~FluentParserStream.html#instance-method-takeChar",
    "src/stream.js~FluentParserStream#takeChar",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#takedigit",
    "class/src/stream.js~FluentParserStream.html#instance-method-takeDigit",
    "src/stream.js~FluentParserStream#takeDigit",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#takehexdigit",
    "class/src/stream.js~FluentParserStream.html#instance-method-takeHexDigit",
    "src/stream.js~FluentParserStream#takeHexDigit",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#takeidchar",
    "class/src/stream.js~FluentParserStream.html#instance-method-takeIDChar",
    "src/stream.js~FluentParserStream#takeIDChar",
    "method"
  ],
  [
    "src/stream.js~fluentparserstream#takeidstart",
    "class/src/stream.js~FluentParserStream.html#instance-method-takeIDStart",
    "src/stream.js~FluentParserStream#takeIDStart",
    "method"
  ],
  [
    "src/stream.js~parserstream#charat",
    "class/src/stream.js~ParserStream.html#instance-method-charAt",
    "src/stream.js~ParserStream#charAt",
    "method"
  ],
  [
    "src/stream.js~parserstream#constructor",
    "class/src/stream.js~ParserStream.html#instance-constructor-constructor",
    "src/stream.js~ParserStream#constructor",
    "method"
  ],
  [
    "src/stream.js~parserstream#currentchar",
    "class/src/stream.js~ParserStream.html#instance-get-currentChar",
    "src/stream.js~ParserStream#currentChar",
    "member"
  ],
  [
    "src/stream.js~parserstream#currentpeek",
    "class/src/stream.js~ParserStream.html#instance-get-currentPeek",
    "src/stream.js~ParserStream#currentPeek",
    "member"
  ],
  [
    "src/stream.js~parserstream#index",
    "class/src/stream.js~ParserStream.html#instance-member-index",
    "src/stream.js~ParserStream#index",
    "member"
  ],
  [
    "src/stream.js~parserstream#next",
    "class/src/stream.js~ParserStream.html#instance-method-next",
    "src/stream.js~ParserStream#next",
    "method"
  ],
  [
    "src/stream.js~parserstream#peek",
    "class/src/stream.js~ParserStream.html#instance-method-peek",
    "src/stream.js~ParserStream#peek",
    "method"
  ],
  [
    "src/stream.js~parserstream#peekoffset",
    "class/src/stream.js~ParserStream.html#instance-member-peekOffset",
    "src/stream.js~ParserStream#peekOffset",
    "member"
  ],
  [
    "src/stream.js~parserstream#resetpeek",
    "class/src/stream.js~ParserStream.html#instance-method-resetPeek",
    "src/stream.js~ParserStream#resetPeek",
    "method"
  ],
  [
    "src/stream.js~parserstream#skiptopeek",
    "class/src/stream.js~ParserStream.html#instance-method-skipToPeek",
    "src/stream.js~ParserStream#skipToPeek",
    "method"
  ],
  [
    "src/stream.js~parserstream#string",
    "class/src/stream.js~ParserStream.html#instance-member-string",
    "src/stream.js~ParserStream#string",
    "member"
  ],
  [
    "src/util.js",
    "file/src/util.js.html",
    "src/util.js",
    "file"
  ],
  [
    "src/visitor.js",
    "file/src/visitor.js.html",
    "src/visitor.js",
    "file"
  ],
  [
    "src/visitor.js~transformer#genericvisit",
    "class/src/visitor.js~Transformer.html#instance-method-genericVisit",
    "src/visitor.js~Transformer#genericVisit",
    "method"
  ],
  [
    "src/visitor.js~transformer#visit",
    "class/src/visitor.js~Transformer.html#instance-method-visit",
    "src/visitor.js~Transformer#visit",
    "method"
  ],
  [
    "src/visitor.js~visitor#genericvisit",
    "class/src/visitor.js~Visitor.html#instance-method-genericVisit",
    "src/visitor.js~Visitor#genericVisit",
    "method"
  ],
  [
    "src/visitor.js~visitor#visit",
    "class/src/visitor.js~Visitor.html#instance-method-visit",
    "src/visitor.js~Visitor#visit",
    "method"
  ]
]