name: legacy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  dist:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14.18']
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}
      - run: npm install --global npm@7
      - run: npm ci
      - run: npm run build --workspaces
      - run: npm test
      - run: npm run lint
      - run: npm run docs --workspaces
